from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

# -------- Base Schema --------
class NoteBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=5000)

# -------- Create Schema --------
class NoteCreate(NoteBase):
    pass  # id and time are generated by DB, not user

# -------- Update Schema --------
class NoteUpdate(BaseModel):
    title: Optional[str] = Field(None, min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=1000)

# -------- Response Schema --------
class NoteResponse(NoteBase):
    id: int
    time: datetime

    class Config:
        orm_mode = True  #  ORM objects TO JSON
